name: Task 2 - Run echo hello world in specific time every day

on:
  schedule:
    - cron: "30 * * * *"
  workflow_dispatch:

jobs:
  scheduleado:
    runs-on: ubuntu-latest
    steps:
      - name: Run hello world
        run: echo 'hello world'