name: Task 1 - Run echo hello world

on:
  push: # El evento que detecta el yaml
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Run hello world
        run: echo 'hello world' # comando de terminal
